#if !defined(__TESTS_SRC_FLEXUNITCOMPILERAPPLICATION_AS)
#define __TESTS_SRC_FLEXUNITCOMPILERAPPLICATION_AS
#if defined(__cplusplus)
/**
*This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
*Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
*/



#include <map>
#include <string>
#include <vector>
#include "Object.h"
#include "Function.h"
#include "Math.h"
#include "Class.h"
#include "RegExp.h"
#include "flash/display/Sprite.h"

namespace tests
{
    class BlendModeTest;
}
namespace tests
{
    class ColorTest;
}
namespace tests
{
    class DelayedCallTest;
}
namespace tests
{
    class DisplayObjectContainerTest;
}
namespace tests
{
    class DisplayObjectTest;
}
namespace tests
{
    class EventTest;
}
namespace tests
{
    class JugglerTest;
}
namespace tests
{
    class MovieClipTest;
}
namespace tests
{
    class QuadTest;
}
namespace tests
{
    class RectangleUtilTest;
}
namespace tests
{
    class TextureAtlasTest;
}
namespace tests
{
    class TextureTest;
}
namespace tests
{
    class TweenTest;
}
namespace tests
{
    class UtilsTest;
}
namespace tests
{
    class VertexDataTest;
}

using namespace flash::display;
using namespace tests;
using namespace tests;
using namespace tests;
using namespace tests;
using namespace tests;
using namespace tests;
using namespace tests;
using namespace tests;
using namespace tests;
using namespace tests;
using namespace tests;
using namespace tests;
using namespace tests;
using namespace tests;
using namespace tests;

class FlexUnitCompilerApplication: public Sprite
{

private:
    tests::BlendModeTest *tests_BlendModeTest_obj;
private:
    tests::MovieClipTest *tests_MovieClipTest_obj;
private:
    tests::TextureTest *tests_TextureTest_obj;
private:
    tests::VertexDataTest *tests_VertexDataTest_obj;
private:
    tests::TweenTest *tests_TweenTest_obj;
private:
    tests::ColorTest *tests_ColorTest_obj;
private:
    tests::TextureAtlasTest *tests_TextureAtlasTest_obj;
private:
    tests::RectangleUtilTest *tests_RectangleUtilTest_obj;
private:
    tests::DisplayObjectContainerTest *tests_DisplayObjectContainerTest_obj;
private:
    tests::QuadTest *tests_QuadTest_obj;
private:
    tests::UtilsTest *tests_UtilsTest_obj;
private:
    tests::DelayedCallTest *tests_DelayedCallTest_obj;
private:
    tests::DisplayObjectTest *tests_DisplayObjectTest_obj;
private:
    tests::JugglerTest *tests_JugglerTest_obj;
private:
    tests::EventTest *tests_EventTest_obj;
};

#endif // __TESTS_SRC_FLEXUNITCOMPILERAPPLICATION_AS
#endif // __cplusplus

