/**
*This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
*Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
*/



#include "FlexUnitCompilerApplication.h"
#include "flash/display/Sprite.h"

#include "tests/BlendModeTest.h"
#include "tests/ColorTest.h"
#include "tests/DelayedCallTest.h"
#include "tests/DisplayObjectContainerTest.h"
#include "tests/DisplayObjectTest.h"
#include "tests/EventTest.h"
#include "tests/JugglerTest.h"
#include "tests/MovieClipTest.h"
#include "tests/QuadTest.h"
#include "tests/RectangleUtilTest.h"
#include "tests/TextureAtlasTest.h"
#include "tests/TextureTest.h"
#include "tests/TweenTest.h"
#include "tests/UtilsTest.h"
#include "tests/VertexDataTest.h"

using namespace flash::display;
using namespace tests;




                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    

